"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { PremiumCard, StatCard } from "@/components/os-ui";
import { authenticatedFetch, readApiJson } from "@/lib/authenticated-fetch";

type WalletRow={user_id:string;balance:number;updated_at:string};type ProfileLite={id:string;full_name:string|null;username:string|null};type LedgerEntry={id:string;transaction_type:string;amount:number;balance_after:number;source:string|null;reference_id:string|null;created_at:string};
const when=(iso:string)=>new Date(iso).toLocaleDateString("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});

export default function FlowsAdminPage(){
 const [wallets,setWallets]=useState<WalletRow[]>([]),[profiles,setProfiles]=useState<Record<string,ProfileLite>>({}),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[selectedUserId,setSelectedUserId]=useState<string|null>(null),[ledger,setLedger]=useState<LedgerEntry[]>([]),[ledgerLoading,setLedgerLoading]=useState(false);
 const load=async()=>{setLoading(true);setError(null);const {supabase}=await import("@/lib/supabase");const {data,error:walletsError}=await supabase.from("flows_wallets").select("user_id,balance,updated_at").order("balance",{ascending:false}).limit(200);if(walletsError){setError(walletsError.message);setLoading(false);return}const rows=(data??[]) as WalletRow[],ids=rows.map(r=>r.user_id);const {data:pr}=ids.length?await supabase.from("profiles").select("id,full_name,username").in("id",ids):{data:[] as ProfileLite[]};setProfiles(Object.fromEntries((pr??[]).map(p=>[p.id,p])));setWallets(rows);setLoading(false)};
 useEffect(()=>{void load()},[]);const total=useMemo(()=>wallets.reduce((s,w)=>s+w.balance,0),[wallets]);
 const openLedger=async(userId:string)=>{setSelectedUserId(userId);setLedgerLoading(true);setError(null);try{const r=await authenticatedFetch(`/api/admin/flows?userId=${userId}`);const p=await readApiJson<{ledger:LedgerEntry[]}>(r);setLedger(p.ledger)}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar el historial.")}finally{setLedgerLoading(false)}};
 return <div className="space-y-4"><PremiumCard className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold">FLOWS</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-white/50">El saldo es una proyección rápida. La emisión real nace únicamente de una operación económica confirmada y de activos FLOW individuales trazables.</p></div><div className="flex flex-wrap gap-2"><Link href="/admin/flows/tesoreria" className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold">Tesorería / Respaldo</Link><Link href="/admin/flows/pagos-manuales" className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black">Registrar pago en efectivo</Link></div></div></PremiumCard>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><StatCard label="FLOWS en circulación" value={loading?"…":total.toLocaleString("es-AR")}/><StatCard label="Wallets con saldo" value={loading?"…":wallets.filter(w=>w.balance>0).length}/><StatCard label="Wallets totales" value={loading?"…":wallets.length}/></div>{error?<p className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>:null}
 <div className="grid gap-4 lg:grid-cols-2"><PremiumCard className="p-5"><h3 className="text-sm uppercase tracking-[0.16em] text-white/50">Saldos derivados</h3>{loading?<p className="mt-3 text-sm text-white/50">Cargando…</p>:null}<div className="mt-3 space-y-2">{wallets.map(w=><button key={w.user_id} onClick={()=>void openLedger(w.user_id)} className={`flex w-full items-center justify-between rounded-xl border px-3 py-2 text-left text-sm ${selectedUserId===w.user_id?"border-violet-400/40 bg-violet-400/10":"border-white/10 bg-black/20"}`}><span>{profiles[w.user_id]?.full_name||profiles[w.user_id]?.username||w.user_id.slice(0,8)}</span><b>{w.balance.toLocaleString("es-AR")} FLOWS</b></button>)}</div></PremiumCard>
 <PremiumCard className="p-5"><h3 className="text-sm uppercase tracking-[0.16em] text-white/50">Historial auditable</h3>{!selectedUserId?<p className="mt-3 text-sm text-white/50">Elegí un usuario para ver los movimientos.</p>:<div className="mt-3 max-h-[420px] space-y-1.5 overflow-y-auto">{ledgerLoading?<p className="text-sm text-white/50">Cargando…</p>:null}{ledger.map(e=><div key={e.id} className="rounded-lg border border-white/[0.07] bg-white/[0.02] px-3 py-2 text-xs"><div className="flex justify-between gap-3"><span className="text-white/65">{e.source||e.transaction_type} · {when(e.created_at)}</span><span className={e.amount>0?"text-emerald-300":"text-red-300"}>{e.amount>0?"+":""}{e.amount} → {e.balance_after}</span></div>{e.reference_id?<p className="mt-1 truncate font-mono text-[10px] text-white/25">Operación {e.reference_id}</p>:null}</div>)}</div>}<div className="mt-4 border-t border-white/10 pt-4 text-xs leading-5 text-white/40">No existe un botón de “agregar FLOW”. Para acreditar saldo, registrá una operación económica real; la emisión ocurre como consecuencia.</div></PremiumCard></div></div>;
}
