import type { CSSProperties, ReactNode } from "react";
import Link from "next/link";
import { PublicMediaGallery } from "./PublicMediaGallery";
import { PublicShareButton } from "./PublicShareButton";
import { PublicSocialLinks } from "./PublicSocialLinks";
import { StudioServicesCart } from "./StudioServicesCart";
import { StudioManageButton } from "./StudioManageButton";
import { formatPlanPrice, studioSocialLinks } from "./StudioPublicView";
import { CustomShell, LAYOUT_ICON_MAP, RADIUS_CLASS, SECTION_ANCHOR, SECTION_NAV_LABEL, renderMusicSection } from "./StudioLayoutRenderer";
import type {
  BlurPreset, ButtonStyle, Decoration, FontFamilyToken, HeaderConfig, ImageFit, ImagePosition, LayoutConfig, LayoutSectionType,
  PositionedElement, PreciseSection, RealAction, ShadowPreset,
} from "@/lib/server/layout-config";
import type { PlayerMedia, StudioMembershipPlan, StudioPlayer, StudioRow, StudioService } from "@/lib/players-data";

type CustomNavLink = { label:string; href:string };
const BUTTON_STYLE_CLASS:Record<ButtonStyle,string>={solid:"bg-[color:var(--public-accent)] text-white hover:opacity-90",outline:"border border-white/20 bg-black/30 text-white hover:border-[color:var(--public-accent)]/60",gradient:"bg-gradient-to-r from-[color:var(--public-accent)] to-black text-white hover:opacity-90",glow:"border border-[color:var(--public-accent)]/60 bg-black/40 text-white shadow-[0_0_24px_-4px_var(--public-accent)]"};
const IMAGE_FIT_CLASS:Record<ImageFit,string>={cover:"object-cover",contain:"object-contain"};
const IMAGE_POSITION_CLASS:Record<ImagePosition,string>={center:"object-center",top:"object-top",bottom:"object-bottom",left:"object-left",right:"object-right"};
const SHADOW_STYLE:Record<ShadowPreset,string|undefined>={none:undefined,soft:"0 8px 28px rgba(0,0,0,.18)",medium:"0 16px 44px rgba(0,0,0,.28)",strong:"0 24px 72px rgba(0,0,0,.42)",glow:"0 0 32px color-mix(in srgb, var(--public-accent) 55%, transparent)"};
const BLUR_STYLE:Record<BlurPreset,string|undefined>={none:undefined,soft:"blur(6px)",medium:"blur(12px)",strong:"blur(20px)"};
const FONT_STACK:Record<FontFamilyToken,string>={system:'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',display:'"Arial Black", Impact, ui-sans-serif, system-ui, sans-serif',editorial:'Georgia, "Times New Roman", serif',sans:'Arial, Helvetica, ui-sans-serif, sans-serif',condensed:'"Arial Narrow", "Roboto Condensed", Arial, sans-serif',mono:'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',serif:'Georgia, Cambria, "Times New Roman", serif'};

function objectPosition(position:ImagePosition|null|undefined):CSSProperties["objectPosition"]{switch(position){case"top":return"center top";case"bottom":return"center bottom";case"left":return"left center";case"right":return"right center";default:return"center center";}}
function recordValue(value:unknown){return value&&typeof value==="object"?value as Record<string,unknown>:{};}

export function PreciseStudioLayoutRenderer({studio,players,media,projects,matrixDiscoveryProjects=[],services,membershipPlans=[],joined=false,layout}:{studio:StudioRow;players:StudioPlayer[];media:PlayerMedia[];projects:Array<Record<string,unknown>>;matrixDiscoveryProjects?:Array<Record<string,unknown>>;services:StudioService[];membershipPlans?:StudioMembershipPlan[];joined?:boolean;layout:LayoutConfig}){
  const isV2Plus=(layout.schema_version??1)>=2,isV3=layout.schema_version===3;
  const headerOverlay=layout.page_style?.header_overlay??false,links=studioSocialLinks(studio),musicLinks=links.filter((link)=>link.platform==="spotify"||link.platform==="youtube");
  const defaultMembershipPlan=membershipPlans.find((plan)=>plan.is_free)??membershipPlans[0]??null;
  const joinHref=defaultMembershipPlan?`/studios/${studio.slug}/checkout${defaultMembershipPlan.is_free?"":`?plan=${defaultMembershipPlan.slug}`}`:`/studios/${studio.slug}/join`;
  const hasRoster=layout.precise_sections.some((section)=>section.type==="roster");
  const sections:PreciseSection[]=players.length&&!hasRoster?[...layout.precise_sections,{type:"roster",heightVh:60,elements:[],styleHint:{heading:"Players",cardStyle:"bordered"}}]:layout.precise_sections;
  const includedTypes=new Set(sections.map((section)=>section.type)),radiusClass=RADIUS_CLASS[layout.page_style?.radius??"medium"],joinTargetHref=joined&&includedTypes.has("roster")?`#${SECTION_ANCHOR.roster}`:joinHref;
  const headerJoinAction={label:joined?"Ya sos miembro":"Unirme",href:joinTargetHref};
  const navLinks:CustomNavLink[]=layout.nav_items?.length?layout.nav_items.map((item)=>({label:item.label,href:`#${SECTION_ANCHOR[item.section]}`})):sections.filter((section)=>section.type!=="hero").map((section)=>({label:SECTION_NAV_LABEL[section.type],href:`#${SECTION_ANCHOR[section.type]}`}));
  if(players.length&&includedTypes.has("roster")&&!navLinks.some((link)=>link.href===`#${SECTION_ANCHOR.roster}`))navLinks.push({label:"Players",href:`#${SECTION_ANCHOR.roster}`});
  const footer=layout.footer&&includedTypes.has(layout.footer.cta_section)?<div className="mx-auto flex max-w-6xl flex-col items-center gap-3 sm:flex-row sm:justify-between"><p className="text-sm text-white/60">{layout.footer.heading}</p><Link href={`#${SECTION_ANCHOR[layout.footer.cta_section]}`} className="rounded-xl bg-[color:var(--public-accent)] px-5 py-2.5 text-sm font-semibold text-white">{layout.footer.cta_label}</Link></div>:undefined;

  function resolveScrollHref(target:LayoutSectionType){return includedTypes.has(target)?`#${SECTION_ANCHOR[target]}`:null;}
  function boxStyle(element:PositionedElement,absolute:boolean):CSSProperties{
    const style:CSSProperties=absolute?{position:"absolute",left:`${element.x}%`,top:`${element.y}%`,width:`${element.w}%`,overflowWrap:"break-word"}:{width:element.mobile?.w?`${element.mobile.w}%`:undefined,order:element.mobile?.order??undefined,alignSelf:element.mobile?.align==="center"?"center":element.mobile?.align==="right"?"flex-end":"flex-start"};
    if(absolute&&element.h!=null)style.height=`${element.h}%`;if(element.zIndex!=null)style.zIndex=element.zIndex;if(element.fontSizePx)style.fontSize=`${element.fontSizePx}px`;if(element.fontWeight)style.fontWeight=element.fontWeight;if(element.fontFamilyToken)style.fontFamily=FONT_STACK[element.fontFamilyToken];if(element.textTransform)style.textTransform=element.textTransform;if(element.color)style.color=element.color;if(element.align)style.textAlign=element.align;if(element.letterSpacingPx!=null)style.letterSpacing=`${element.letterSpacingPx}px`;if(element.lineHeight!=null)style.lineHeight=element.lineHeight;if(element.opacity!=null)style.opacity=element.opacity;return style;
  }
  function surfaceStyle(element:PositionedElement):CSSProperties{const style:CSSProperties={};if(element.backgroundColor)style.backgroundColor=element.backgroundColor;if(element.borderColor)style.borderColor=element.borderColor;if(element.borderWidthPx!=null){style.borderWidth=`${element.borderWidthPx}px`;style.borderStyle="solid";}if(element.radiusPx!=null)style.borderRadius=`${element.radiusPx}px`;if(element.shadow)style.boxShadow=SHADOW_STYLE[element.shadow];if(element.blur)style.backdropFilter=BLUR_STYLE[element.blur];return style;}
  function actionHref(action:RealAction|null|undefined){if(action==="join")return joinTargetHref;if(action?.startsWith("scroll:"))return resolveScrollHref(action.slice(7) as LayoutSectionType);return null;}
  function renderActionButton(element:PositionedElement):ReactNode{
    const label=element.text||"Unirme",action=element.action,Icon=element.icon?LAYOUT_ICON_MAP[element.icon]:null,icon=Icon?<Icon className="h-4 w-4"/>:null;
    if(action==="share")return <PublicShareButton title={studio.name}/>;const styleClass=BUTTON_STYLE_CLASS[element.buttonStyle??(action==="join"?"solid":"outline")],visualStyle:CSSProperties=isV2Plus?{...surfaceStyle(element),width:"100%",height:"100%",minHeight:element.h?undefined:"38px",padding:element.h?"0 12px":"8px 16px"}:{},common=isV2Plus?`inline-flex items-center justify-center gap-2 text-sm font-semibold transition ${styleClass}`:`inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold transition ${styleClass}`;const href=actionHref(action);return href?<Link href={href} className={common} style={visualStyle}>{icon}{action==="join"&&joined?"Ya sos miembro":label}</Link>:<span className={`${common} opacity-80`} style={visualStyle}>{icon}{label}</span>;
  }

  function renderDecoration(decoration:Decoration,index:number):ReactNode{
    const style:CSSProperties={position:"absolute",left:`${decoration.x}%`,top:`${decoration.y}%`,width:decoration.w?`${decoration.w}%`:undefined,height:decoration.h?`${decoration.h}%`:undefined,zIndex:decoration.zIndex??undefined,opacity:decoration.opacity??undefined,color:decoration.color??undefined,backgroundColor:decoration.backgroundColor??undefined,borderColor:decoration.borderColor??undefined,borderWidth:decoration.borderWidthPx!=null?`${decoration.borderWidthPx}px`:undefined,borderStyle:decoration.borderWidthPx?"solid":undefined,borderRadius:decoration.radiusPx!=null?`${decoration.radiusPx}px`:undefined,filter:decoration.blur?BLUR_STYLE[decoration.blur]:undefined};const key=decoration.id??index;
    switch(decoration.type){case"waveform":return <div key={key} style={style} className="flex items-end gap-[3px]">{Array.from({length:24}).map((_,i)=><span key={i} className="w-[3px] rounded-full bg-white/60" style={{height:`${8+(i*37)%20}px`}}/>)}</div>;case"scroll-indicator":return <div key={key} style={style} className="flex flex-col items-center gap-2 text-[10px] uppercase tracking-[.2em] text-white/60"><span className="flex h-8 w-5 items-start justify-center rounded-full border border-white/40 p-1"><span className="h-1.5 w-1.5 rounded-full bg-white/70"/></span>Scroll</div>;case"vertical-label":return decoration.text?<div key={key} style={{...style,writingMode:"vertical-rl"}} className="text-[10px] uppercase tracking-[.3em] text-white/40">{decoration.text}</div>:null;case"divider-line":case"line":return <div key={key} style={{...style,backgroundColor:decoration.color||decoration.backgroundColor||"rgba(255,255,255,.18)"}}/>;case"circle":return <div key={key} style={{...style,borderRadius:"999px",backgroundColor:decoration.backgroundColor||"rgba(255,255,255,.08)"}}/>;case"rectangle":case"gradient-block":case"glow":return <div key={key} style={style}/>;default:return null;}
  }

  function projectAt(index:number|null|undefined){return projects[index??0]??projects[0]??null;}
  function renderProjectCard(project:Record<string,unknown>|null,compact=false):ReactNode{if(!project)return <div className="flex h-full items-center justify-center border border-white/10 bg-white/[.025] text-sm text-white/40">Sin lanzamientos todavía</div>;const title=String(project.title||"Lanzamiento"),cover=typeof project.cover_url==="string"?project.cover_url:null,spotify=typeof project.spotify_url==="string"?project.spotify_url:null,youtube=typeof project.youtube_url==="string"?project.youtube_url:null,href=spotify||youtube;return <article className={`h-full overflow-hidden border border-white/10 bg-black/35 ${compact?"flex items-center gap-3 p-3":""}`}>{cover?<img src={cover} alt="" className={compact?"h-16 w-16 shrink-0 object-cover":"aspect-square w-full object-cover"}/>:null}<div className={compact?"min-w-0":"p-4"}><p className="truncate font-semibold text-white">{title}</p><p className="mt-1 text-xs text-white/45">{studio.name}</p>{href?<a href={href} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-xs font-semibold text-[color:var(--public-accent)]">Escuchar</a>:<span className="mt-3 block text-xs text-white/35">Sin reproducción disponible</span>}</div></article>;}
  function renderDynamicWidget(element:PositionedElement):ReactNode{
    const widget=element.widget,index=element.dataIndex??0,variant=element.variant??"default",compact=variant==="compact"||variant==="list";
    if(!widget)return null;
    if(widget==="now-playing"||widget==="featured-release"||widget==="release-card"||widget==="project-card")return <div className="h-full w-full">{renderProjectCard(projectAt(index),compact)}</div>;
    if(widget==="player-card"){const entry=players[index]??players[0];if(!entry?.player)return <div className="h-full border border-dashed border-white/15 p-4 text-white/40">Sin Player</div>;return <Link href={`/${entry.player.slug}`} className="flex h-full items-center gap-3 border border-white/10 bg-black/30 p-3">{entry.player.profile_image_url?<img src={entry.player.profile_image_url} alt="" className="h-14 w-14 rounded-xl object-cover"/>:<span className="grid h-14 w-14 place-items-center rounded-xl bg-white/10">{entry.player.display_name.charAt(0)}</span>}<div className="min-w-0"><p className="truncate font-semibold">{entry.player.display_name}</p><p className="text-xs text-white/45">{entry.role||"Player"}</p></div></Link>;}
    if(widget==="player-grid"){const cols=element.columns??3;return <div className="grid h-full" style={{gridTemplateColumns:`repeat(${cols},minmax(0,1fr))`,gap:`${element.gapPx??12}px`}}>{players.slice(0,Math.max(cols*2,cols)).map((entry,i)=>entry.player?<Link key={`${entry.player.id}-${i}`} href={`/${entry.player.slug}`} className="min-w-0 border border-white/10 bg-black/30 p-3">{entry.player.profile_image_url?<img src={entry.player.profile_image_url} alt="" className="aspect-square w-full object-cover"/>:null}<p className="mt-2 truncate text-sm font-semibold">{entry.player.display_name}</p></Link>:null)}</div>;}
    if(widget==="service-card"){const service=services[index]??services[0];if(!service)return <div className="h-full border border-dashed border-white/15 p-4 text-white/40">Sin servicios</div>;const row=recordValue(service);return <article className="h-full border border-white/10 bg-black/30 p-4"><h3 className="font-semibold">{String(row.name||"Servicio")}</h3>{row.description?<p className="mt-2 text-sm text-white/55">{String(row.description)}</p>:null}</article>;}
    if(widget==="membership-card"){const plan=membershipPlans[index]??membershipPlans[0];if(!plan)return <div className="h-full border border-dashed border-white/15 p-4 text-white/40">Sin membresías</div>;return <article className="flex h-full flex-col border border-white/10 bg-black/30 p-4"><h3 className="font-semibold">{plan.name}</h3>{plan.description?<p className="mt-2 text-sm text-white/55">{plan.description}</p>:null}<p className="mt-3 text-xl font-bold">{formatPlanPrice(plan)}</p><Link href={`/studios/${studio.slug}/checkout${plan.is_free?"":`?plan=${plan.slug}`}`} className="mt-auto bg-[color:var(--public-accent)] px-4 py-2 text-center text-xs font-semibold">{plan.is_free?"Unirme gratis":"Elegir plan"}</Link></article>;}
    if(widget==="gallery-item"||widget==="media-card"){const item=media[index]??media[0],row=recordValue(item);const src=typeof row.public_url==="string"?row.public_url:typeof row.thumbnail_url==="string"?row.thumbnail_url:typeof row.source_url==="string"?row.source_url:null;return src?<img src={src} alt="" className="h-full w-full object-cover"/>:<div className="h-full border border-dashed border-white/15"/>;}
    if(widget==="social-link"){const link=links[index]??links[0];return link?<a href={link.url} target="_blank" rel="noreferrer" className="inline-flex h-full w-full items-center justify-center border border-white/15 bg-black/25 text-sm font-semibold uppercase tracking-[.12em]">{link.platform}</a>:null;}
    if(widget==="cta")return <Link href={joinTargetHref} className="inline-flex h-full w-full items-center justify-center bg-[color:var(--public-accent)] text-sm font-semibold">{element.text||headerJoinAction.label}</Link>;
    if(widget==="stat"){const value=element.text||`${players.length}`;return <div className="flex h-full w-full flex-col justify-center"><strong className="text-3xl">{value}</strong></div>;}
    if(widget==="section-title")return <h2 className="flex h-full items-center text-2xl font-semibold">{element.text||""}</h2>;
    return null;
  }

  function renderElement(element:PositionedElement,index:number,absolute:boolean):ReactNode{
    if(!absolute&&element.mobile?.hidden)return null;const style=boxStyle(element,absolute),merged=isV2Plus?{...style,...surfaceStyle(element)}:style,key=element.id??index;
    switch(element.type){case"dynamic":return <div key={key} style={merged}>{renderDynamicWidget(element)}</div>;case"image":{const src=element.imageSlot?layout.image_slots[element.imageSlot]:undefined;if(!src)return null;return <img key={key} src={src} alt="" style={{...merged,objectFit:element.imageFit??"cover",objectPosition:objectPosition(element.imagePosition)}} className={absolute?"pointer-events-none":"block max-w-full"}/>;}case"button":return <div key={key} style={style}>{renderActionButton(element)}</div>;case"badge":return element.text?<span key={key} style={merged} className={isV2Plus?"inline-flex items-center":"inline-block rounded-full border border-white/20 px-3 py-1 text-xs"}>{element.text}</span>:null;case"eyebrow":return element.text?<p key={key} style={merged}>{element.text}</p>:null;case"heading":return element.text?<h1 key={key} style={merged} className={isV2Plus?"text-white":"font-bold text-white"}>{element.text}</h1>:null;case"subheading":return element.text?<h2 key={key} style={merged} className="text-white/85">{element.text}</h2>:null;case"paragraph":default:return element.text?<p key={key} style={merged} className="text-white/70">{element.text}</p>:null;}
  }

  function sectionOuterStyle(section:PreciseSection):CSSProperties{const style:CSSProperties={height:`${section.heightVh}vh`,minHeight:`${section.heightVh}vh`,backgroundColor:section.background?.color||"#07060b"};if(isV2Plus&&section.widthPct&&section.widthPct<99.5)style.width=`${section.widthPct}%`;if(isV2Plus&&section.xPct)style.marginLeft=`${section.xPct}%`;return style;}
  function renderSectionBackground(section:PreciseSection):ReactNode{const src=section.background?.imageSlot?layout.image_slots[section.background.imageSlot]:undefined;if(!src)return null;const overlay=isV2Plus?(section.background?.overlayOpacity??0):.35;return <><img src={src} alt="" className={`absolute inset-0 h-full w-full ${IMAGE_FIT_CLASS[section.background?.fit??"cover"]} ${IMAGE_POSITION_CLASS[section.background?.position??"center"]}`}/>{overlay>0?<div className="absolute inset-0 bg-black" style={{opacity:overlay}}/>:null}</>;}
  function renderStaticSection(section:PreciseSection,index:number):ReactNode{const elements=section.elements??[],decorations=section.decorations??[];return <section key={section.id??index} id={SECTION_ANCHOR[section.type]} className={`relative md:overflow-hidden ${isV2Plus?"":"w-full border-b border-white/10"}`} style={sectionOuterStyle(section)}>{renderSectionBackground(section)}<div className="relative hidden h-full md:block"><div className="absolute inset-0">{elements.map((e,i)=>renderElement(e,i,true))}{decorations.map((d,i)=>renderDecoration(d,i))}</div></div><div className="relative flex flex-col gap-3 px-5 py-8 md:hidden">{elements.map((e,i)=>renderElement(e,i,false))}</div></section>;}
  function renderColumn(column:PreciseSection,index:number,count:number):ReactNode{const width:CSSProperties=column.widthPct?{flex:`0 0 ${column.widthPct}%`}:{flex:`1 1 ${100/count}%`};if(isV2Plus&&column.xPct)width.marginLeft=`${column.xPct}%`;if(column.styleHint)return <div key={column.id??index} className="relative min-w-0" style={width}>{renderDynamicSection(column,index)}</div>;return <div key={column.id??index} className="relative h-full min-w-0" style={width}>{(column.elements??[]).map((e,i)=>renderElement(e,i,true))}{(column.decorations??[]).map((d,i)=>renderDecoration(d,i))}</div>;}
  function renderColumnsSection(section:PreciseSection,index:number):ReactNode{const columns=section.columns??[];return <section key={section.id??index} id={SECTION_ANCHOR[section.type]} className="relative" style={sectionOuterStyle(section)}>{renderSectionBackground(section)}<div className="relative mx-auto flex h-full max-w-7xl flex-col md:flex-row md:items-stretch" style={{gap:section.styleHint?.gapPx??32,padding:section.styleHint?.paddingPx??40}}>{columns.map((c,i)=>renderColumn(c,i,columns.length))}</div></section>;}
  function dynamicWrapperStyle(section:PreciseSection):CSSProperties{const h=section.styleHint,s:CSSProperties={};if(section.background?.color)s.backgroundColor=section.background.color;if(h?.backgroundColor)s.backgroundColor=h.backgroundColor;if(h?.borderColor){s.borderColor=h.borderColor;s.borderStyle="solid";s.borderWidth="1px";}if(h?.radiusPx!=null)s.borderRadius=`${h.radiusPx}px`;if(h?.paddingPx!=null)s.padding=`${h.paddingPx}px`;if(isV2Plus&&section.widthPct&&section.widthPct<99.5)s.width=`${section.widthPct}%`;if(isV2Plus&&section.xPct)s.marginLeft=`${section.xPct}%`;return s;}
  function dynamicCardStyle(section:PreciseSection):CSSProperties{const h=section.styleHint,s:CSSProperties={};if(h?.cardBackgroundColor)s.backgroundColor=h.cardBackgroundColor;if(h?.cardBorderColor){s.borderColor=h.cardBorderColor;s.borderStyle="solid";s.borderWidth="1px";}if(h?.cardRadiusPx!=null)s.borderRadius=`${h.cardRadiusPx}px`;return s;}
  function renderDynamicSection(section:PreciseSection,index:number):ReactNode{const heading=section.styleHint?.heading,wrapper=dynamicWrapperStyle(section),card=dynamicCardStyle(section),gap=section.styleHint?.gapPx??16,grid:CSSProperties={gap:`${gap}px`};if(section.styleHint?.columns)grid.gridTemplateColumns=`repeat(${section.styleHint.columns},minmax(0,1fr))`;
    switch(section.type){case"roster":return <section key={section.id??index} id={SECTION_ANCHOR.roster} className="mx-auto max-w-6xl px-4 py-10 sm:px-6" style={wrapper}><h2 className="text-2xl font-semibold">{heading||"Players"}</h2>{players.length?<div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-3" style={grid}>{players.map((entry,i)=>entry.player?<Link key={`${entry.player.id}-${i}`} href={`/${entry.player.slug}`} className="flex items-center gap-4 border border-white/10 bg-white/[.025] p-4" style={card}>{entry.player.profile_image_url?<img src={entry.player.profile_image_url} alt="" className="h-16 w-16 object-cover" style={{borderRadius:section.styleHint?.cardRadiusPx??16}}/>:null}<div className="min-w-0"><p className="truncate font-semibold">{entry.player.display_name}</p><p className="text-sm text-white/55">{entry.role||"Player"}</p></div></Link>:null)}</div>:<div className="mt-5 border border-dashed border-white/15 p-8 text-center text-white/45">Próximos Players</div>}</section>;case"services":return services.length?<section key={section.id??index} id={SECTION_ANCHOR.services} className="mx-auto max-w-6xl px-4 py-10 sm:px-6" style={wrapper}><h2 className="text-2xl font-semibold">{heading||"Servicios"}</h2><div className="mt-5"><StudioServicesCart studioId={studio.id} studioSlug={studio.slug} services={services}/></div></section>:null;case"membership":return membershipPlans.length?<section key={section.id??index} id={SECTION_ANCHOR.membership} className="mx-auto max-w-6xl px-4 py-10 sm:px-6" style={wrapper}><h2 className="text-2xl font-semibold">{heading||"Membresías"}</h2><div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-3" style={grid}>{membershipPlans.map((plan)=><article key={plan.id} className="flex flex-col border border-white/10 bg-white/[.025] p-6" style={card}><h3 className="font-semibold">{plan.name}</h3>{plan.description?<p className="mt-3 text-sm text-white/55">{plan.description}</p>:null}<p className="mt-4 text-2xl font-bold">{formatPlanPrice(plan)}</p><Link href={`/studios/${studio.slug}/checkout${plan.is_free?"":`?plan=${plan.slug}`}`} className="mt-6 bg-[color:var(--public-accent)] px-5 py-3 text-center text-sm font-semibold">{plan.is_free?"Unirme gratis":"Elegir plan"}</Link></article>)}</div></section>:null;case"gallery":return media.length?<div key={section.id??index} id={SECTION_ANCHOR.gallery} style={wrapper}><PublicMediaGallery media={media}/></div>:null;case"music":return <div key={section.id??index} style={wrapper}>{renderMusicSection({sectionKey:index,heading,isList:false,maxReleases:6,musicLinks,projects,matrixDiscoveryProjects,studioName:studio.name,radiusClass})}</div>;default:return null;}
  }
  function renderSection(section:PreciseSection,index:number):ReactNode{if(section.columns?.length)return renderColumnsSection(section,index);if(section.styleHint)return renderDynamicSection(section,index);if(section.type==="hero")return <div key={section.id??index}>{renderStaticSection(section,index)}{joined?<div className="mx-auto max-w-6xl px-4 pt-6"><div className="rounded-2xl border border-emerald-400/30 bg-emerald-400/10 px-5 py-4 text-sm">Ya sos miembro de {studio.name}.</div></div>:null}<div className="mx-auto mt-4 max-w-6xl px-4"><StudioManageButton studioId={studio.id}/></div></div>;return renderStaticSection(section,index);}

  const content=sections.map((section,index)=>renderSection(section,index));
  if(!isV3||!layout.header)return <CustomShell brand={studio.name} logoUrl={studio.logo_url} navLinks={navLinks} accent={layout.page_style?.palette?.accent||"#8f7cff"} navStyle={layout.page_style?.nav_style??"pill"} joinAction={headerJoinAction} links={links} footer={footer} headerOverlay={headerOverlay}>{content}</CustomShell>;

  const h=layout.header;
  return <div className="relative min-h-screen bg-[#07060b] text-white" style={{["--public-accent" as string]:layout.page_style?.palette?.accent||"#8f7cff"}}><PreciseHeader config={h} studio={studio} layout={layout} navLinks={navLinks} joinHref={joinTargetHref}/><main>{content}</main><footer className="border-t border-white/10 px-4 py-8 text-center text-xs text-white/40">{links.length?<div className="mb-5 flex justify-center"><PublicSocialLinks links={links}/></div>:null}{footer??`${studio.name} · CLOUVA`}</footer></div>;
}

function PreciseHeader({config,studio,layout,navLinks,joinHref}:{config:HeaderConfig;studio:StudioRow;layout:LayoutConfig;navLinks:CustomNavLink[];joinHref:string}){
  const brandImage=config.brand?.imageSlot?layout.image_slots[config.brand.imageSlot]:studio.logo_url,mode=config.mode,position:CSSProperties["position"]=mode==="sticky"?"sticky":mode==="overlay"||mode==="floating"?"absolute":"relative";
  const style:CSSProperties={position,top:mode==="sticky"?0:config.yPx??0,left:config.xPct?`${config.xPct}%`:0,width:config.widthPct?`${config.widthPct}%`:"100%",height:config.heightPx?`${config.heightPx}px`:undefined,zIndex:40,backgroundColor:config.backgroundColor??(mode==="normal"?"rgba(7,6,11,.92)":"transparent"),opacity:config.opacity??1,backdropFilter:config.blur?BLUR_STYLE[config.blur]:undefined,borderColor:config.borderColor??undefined,borderWidth:config.borderWidthPx?`${config.borderWidthPx}px`:undefined,borderStyle:config.borderWidthPx?"solid":undefined,borderRadius:config.radiusPx?`${config.radiusPx}px`:undefined};
  const navStyle:CSSProperties={gap:`${config.nav?.gapPx??24}px`,fontFamily:config.nav?.fontFamilyToken?FONT_STACK[config.nav.fontFamilyToken]:undefined,fontSize:config.nav?.fontSizePx?`${config.nav.fontSizePx}px`:undefined,textTransform:config.nav?.uppercase?"uppercase":undefined,justifyContent:config.nav?.align==="left"?"flex-start":config.nav?.align==="right"?"flex-end":"center"};
  const ctaAction=config.cta?.action,ctaHref=ctaAction==="join"?joinHref:ctaAction?.startsWith("scroll:")?`#${SECTION_ANCHOR[ctaAction.slice(7) as LayoutSectionType]}`:joinHref;
  return <header style={style}><div className="mx-auto flex h-full min-h-14 max-w-7xl items-center gap-5 px-4 sm:px-6"><Link href="/matrix" className="flex shrink-0 items-center gap-2">{brandImage?<img src={brandImage} alt={studio.name} style={{width:config.brand?.widthPx??32,height:config.brand?.heightPx??32,objectFit:config.brand?.fit??"contain"}}/>:null}{config.brand?.showText!==false?<span className="font-semibold tracking-wide">{studio.name}</span>:null}</Link><nav className="hidden min-w-0 flex-1 items-center md:flex" style={navStyle}>{navLinks.map((link,i)=><Link key={`${link.href}-${i}`} href={link.href} className="whitespace-nowrap text-white/70 transition hover:text-white">{link.label}</Link>)}</nav>{config.cta?<Link href={ctaHref} className={`ml-auto shrink-0 px-4 py-2 text-xs font-semibold ${BUTTON_STYLE_CLASS[config.cta.buttonStyle??"solid"]}`} style={{borderRadius:config.radiusPx??999}}>{config.cta.label||"Unirme"}</Link>:null}</div><nav className="flex gap-1 overflow-x-auto px-3 py-2 text-[11px] text-white/60 md:hidden">{navLinks.map((link,i)=><Link key={`${link.href}-${i}`} href={link.href} className="shrink-0 px-3 py-1.5">{link.label}</Link>)}</nav></header>;
}
