import net from "node:net";
import { NextResponse } from "next/server";
export const runtime="nodejs"; export const dynamic="force-dynamic";
type V={value:number;size:number};
const enc=(n:number)=>{const a:number[]=[];let v=n>>>0;do{let b=v&127;v>>>=7;if(v)b|=128;a.push(b)}while(v);return Buffer.from(a)};
const read=(b:Buffer,o=0):V|null=>{let v=0,p=0;while(p<5){if(o+p>=b.length)return null;const c=b[o+p];v|=(c&127)<<(7*p);p++;if(!(c&128))return{value:v,size:p}}throw new Error("VarInt inválido")};
const str=(s:string)=>{const b=Buffer.from(s);return Buffer.concat([enc(b.length),b])};
function text(d:unknown){if(typeof d==="string")return d;if(!d||typeof d!=="object")return null;const r=d as {text?:unknown;extra?:unknown[]};const a:string[]=[];if(typeof r.text==="string")a.push(r.text);for(const x of Array.isArray(r.extra)?r.extra:[])if(typeof x==="string")a.push(x);else if(x&&typeof x==="object"&&typeof (x as {text?:unknown}).text==="string")a.push(String((x as {text:string}).text));return a.join("").trim()||null}
async function query(host:string,port:number){const start=Date.now();return await new Promise<any>((resolve,reject)=>{const s=net.createConnection({host,port});let all=Buffer.alloc(0),done=false;const end=(e?:Error,v?:any)=>{if(done)return;done=true;s.destroy();(() => { if (e) reject(e); else resolve(v); })()};s.setTimeout(3000);s.on("timeout",()=>end(new Error("timeout")));s.on("error",end);s.on("connect",()=>{const pb=Buffer.allocUnsafe(2);pb.writeUInt16BE(port);const p=Buffer.concat([enc(0),enc(0),str(host),pb,enc(1)]);s.write(Buffer.concat([enc(p.length),p,Buffer.from([1,0])]))});s.on("data",c=>{try{all=Buffer.concat([all,c]);const l=read(all);if(!l||all.length<l.size+l.value)return;const p=all.subarray(l.size,l.size+l.value),id=read(p);if(!id||id.value!==0)throw new Error("Respuesta inesperada");const jl=read(p,id.size);if(!jl)return;const js=id.size+jl.size;if(p.length<js+jl.value)return;const x=JSON.parse(p.subarray(js,js+jl.value).toString()) as any;end(undefined,{latencyMs:Date.now()-start,version:x.version?.name??null,motd:text(x.description),players:{online:Number(x.players?.online??0),max:Number(x.players?.max??0),sample:Array.isArray(x.players?.sample)?x.players.sample.map((q:any)=>q?.name).filter(Boolean):[]}})}catch(e){end(e instanceof Error?e:new Error("Respuesta inválida"))}})})}
export async function GET(){const host=process.env.MINECRAFT_HOST?.trim()||null,javaPort=Number(process.env.MINECRAFT_JAVA_PORT||25565),bedrockPort=Number(process.env.MINECRAFT_BEDROCK_PORT||19132),publicJavaHost=process.env.MINECRAFT_PUBLIC_JAVA_HOST?.trim()||host,publicBedrockHost=process.env.MINECRAFT_PUBLIC_BEDROCK_HOST?.trim()||host,mapUrl=process.env.MINECRAFT_MAP_URL?.trim()||"/minecraft/map/";if(!host)return NextResponse.json({configured:false,online:false,host,publicJavaHost,publicBedrockHost,javaPort,bedrockPort,mapUrl},{headers:{"Cache-Control":"no-store"}});try{return NextResponse.json({configured:true,online:true,host,publicJavaHost,publicBedrockHost,javaPort,bedrockPort,mapUrl,...await query(host,javaPort)},{headers:{"Cache-Control":"no-store"}})}catch(e){return NextResponse.json({configured:true,online:false,host,publicJavaHost,publicBedrockHost,javaPort,bedrockPort,mapUrl,error:e instanceof Error?e.message:"No se pudo consultar Minecraft"},{headers:{"Cache-Control":"no-store"}})}}
