import { PORTFOLIO_ASSETS, type PortfolioLocale, type PortfolioStatus } from "@/lib/portfolio/portfolio-data";

export const PORTFOLIO_V3_ASSETS = {
  home: PORTFOLIO_ASSETS.homeMobile,
  publicSystem: PORTFOLIO_ASSETS.hero,
  player: PORTFOLIO_ASSETS.player,
  market: PORTFOLIO_ASSETS.market,
  creator: "/reference/male-front.png",
  ai: "/assets/clouva-ai/trebol-mascot.png",
} as const;

export const PORTFOLIO_V3_COPY = {
  en: {
    hero: {
      name: "SERGIO IBAÑEZ",
      role: "AI-NATIVE PRODUCT BUILDER",
      headline: "I build digital products where AI, product, cloud and creative technology work together.",
      lead: "I turn product ideas into working systems using design, AI-assisted development, cloud infrastructure and creative technology.",
      location: "Buenos Aires, Argentina",
      availability: "AVAILABLE FOR OPPORTUNITIES",
      availableFor: "Available for",
      roles: ["Frontend", "Product", "AI Product", "Creative Technology"],
      viewWork: "View work",
      viewClouva: "View CLOUVA",
      currentBuild: "CLOUVA / CURRENT BUILD",
      evidence: "REAL PRODUCT ASSET",
      liveSurface: "LIVE PRODUCT SURFACE",
      productView: "HOME / PRODUCT SHELL",
      creatorView: "CREATOR / DEVELOPMENT PIPELINE",
      playerView: "PLAYER / IDENTITY SYSTEM",
    },
    flagship: {
      index: "01 / FLAGSHIP PRODUCT",
      title: "CLOUVA",
      subtitle: "Creative Operating System",
      body: "One connected product ecosystem for identity, music, AI, creator tools, money, commerce, cloud infrastructure and 3D workflows.",
      visualLabel: "REAL CLOUVA PRODUCT ASSETS",
      visualNote: "Product surfaces and assets from the current CLOUVA system.",
      annotations: ["SHARED NAVIGATION", "RESPONSIVE PRODUCT SHELL", "PUBLIC / AUTHENTICATED STATES", "PLAYER", "MI FLOW", "MARKET"],
      roles: "ROLE",
      stack: "STACK",
      architecture: "SYSTEM ARCHITECTURE",
      live: "Open CLOUVA",
    },
    snapshot: {
      eyebrow: "PRODUCT SNAPSHOT",
      title: "One product. Five connected domains.",
      intro: "CLOUVA is structured as connected product domains rather than isolated screens.",
      items: [
        ["01", "IDENTITY", "Player", "Public identity + music"],
        ["02", "MONEY", "Mi Flow", "Backing + ledger"],
        ["03", "CREATION", "AI + Creator Studio", "Tools + 3D pipeline"],
        ["04", "COMMERCE", "Market + Mi Spot", "Products + services"],
        ["05", "INFRASTRUCTURE", "Supabase + Google Cloud", "Data + assets + deploy"],
      ],
    },
    statement: {
      eyebrow: "PRODUCT THINKING",
      lineOne: "I didn't build isolated screens.",
      lineTwo: "I built one connected product system.",
      capabilities: ["PRODUCT", "DESIGN", "FRONTEND", "CLOUD", "AI", "3D", "AUTOMATION"],
    },
    featured: {
      index: "02 / FEATURED SYSTEMS",
      title: "Three systems that show how I think.",
      intro: "The interface matters, but the rules underneath it matter more. These cases expose the product decisions behind CLOUVA.",
      problem: "PROBLEM",
      decision: "SYSTEM DECISION",
      rail: "REAL RAIL / STACK",
      items: [
        {
          id: "flow",
          status: "IN DEVELOPMENT" as PortfolioStatus,
          eyebrow: "MONEY / SYSTEM DESIGN",
          title: "Mi Flow",
          problem: "Internal value needs to stay auditable without becoming the same thing as real-money payment state.",
          decision: "Separate payment backing from emission, ledger history and available FLOW. 1 FLOW uses USD 1 as a reference value.",
          rail: "Mercado Pago remains the real payment rail · Supabase · PostgreSQL",
          pipeline: ["BACKING", "EMISSION", "LEDGER", "AVAILABLE FLOW"],
          image: null,
          imageAlt: "",
          evidenceLabel: "SYSTEM DIAGRAM",
        },
        {
          id: "creator",
          status: "IN DEVELOPMENT" as PortfolioStatus,
          eyebrow: "3D / CREATOR TOOLS",
          title: "Creator Studio",
          problem: "Garments and avatars need measurable, repeatable preparation before they can enter a real-time 3D pipeline.",
          decision: "Use GLB assets, landmarks, measurements, validation, fitting and Blender processing as a canonical preparation flow.",
          rail: "GLB · landmarks · measurements · Blender · Unreal pipeline",
          pipeline: ["GARMENT", "ANALYSIS", "VALIDATION", "FIT", "RIG", "EXPORT", "UNREAL"],
          image: PORTFOLIO_V3_ASSETS.creator,
          imageAlt: "Real Creator Studio body reference asset from the CLOUVA repository",
          evidenceLabel: "DEVELOPMENT PIPELINE",
        },
        {
          id: "ai",
          status: "IN DEVELOPMENT" as PortfolioStatus,
          eyebrow: "AI / PRODUCT SYSTEM",
          title: "CLOUVA AI",
          problem: "AI inside a product needs context, tools and action boundaries—not only chat output.",
          decision: "Route user intent through context and tools, requiring confirmation when an action has consequences.",
          rail: "Gemini · multimodal · tool execution · confirmation boundaries · Trébol in development",
          pipeline: ["USER INTENT", "CONTEXT", "CLOUVA AI", "TOOLS", "CONFIRMATION", "ACTION"],
          image: PORTFOLIO_V3_ASSETS.ai,
          imageAlt: "Official Trébol visual asset used by CLOUVA AI",
          evidenceLabel: "REAL PRODUCT ASSET",
        },
      ],
    },
    about: {
      eyebrow: "SERGIO / PRODUCT BUILDER",
      title: "I work across the boundaries that usually split a product apart.",
      body: "Product direction, interface design, frontend, AI-assisted implementation, cloud infrastructure and creative technology come together in the same build process.",
      proof: "CLOUVA is the working proof: an evolving product where I define functionality, connect systems, validate implementations and iterate on the real architecture.",
    },
    deepDive: {
      index: "03 / SYSTEM DEEP DIVE",
      title: "Explore the rest of the product.",
      intro: "Core and supporting systems are shown with honest LIVE / IN DEVELOPMENT / PLANNED states and direct product links where available.",
    },
  },
  es: {
    hero: {
      name: "SERGIO IBAÑEZ",
      role: "AI-NATIVE PRODUCT BUILDER",
      headline: "Construyo productos digitales donde IA, producto, cloud y tecnología creativa trabajan juntos.",
      lead: "Convierto ideas de producto en sistemas funcionales usando diseño, desarrollo asistido por IA, infraestructura cloud y tecnología creativa.",
      location: "Buenos Aires, Argentina",
      availability: "DISPONIBLE PARA OPORTUNIDADES",
      availableFor: "Disponible para",
      roles: ["Frontend", "Product", "AI Product", "Creative Technology"],
      viewWork: "Ver trabajo",
      viewClouva: "Ver CLOUVA",
      currentBuild: "CLOUVA / BUILD ACTUAL",
      evidence: "ASSET REAL DEL PRODUCTO",
      liveSurface: "SUPERFICIE LIVE DEL PRODUCTO",
      productView: "HOME / PRODUCT SHELL",
      creatorView: "CREATOR / PIPELINE EN DESARROLLO",
      playerView: "PLAYER / SISTEMA DE IDENTIDAD",
    },
    flagship: {
      index: "01 / PRODUCTO PRINCIPAL",
      title: "CLOUVA",
      subtitle: "Creative Operating System",
      body: "Un ecosistema de producto conectado para identidad, música, IA, herramientas creativas, dinero, commerce, infraestructura cloud y flujos 3D.",
      visualLabel: "ASSETS REALES DE PRODUCTO CLOUVA",
      visualNote: "Superficies y assets del producto actual de CLOUVA.",
      annotations: ["NAVEGACIÓN COMPARTIDA", "PRODUCT SHELL RESPONSIVE", "ESTADOS PÚBLICOS / AUTENTICADOS", "PLAYER", "MI FLOW", "MARKET"],
      roles: "ROL",
      stack: "STACK",
      architecture: "ARQUITECTURA DEL SISTEMA",
      live: "Abrir CLOUVA",
    },
    snapshot: {
      eyebrow: "PRODUCT SNAPSHOT",
      title: "Un producto. Cinco dominios conectados.",
      intro: "CLOUVA está estructurado como dominios de producto conectados y no como pantallas aisladas.",
      items: [
        ["01", "IDENTIDAD", "Player", "Identidad pública + música"],
        ["02", "DINERO", "Mi Flow", "Backing + ledger"],
        ["03", "CREACIÓN", "AI + Creator Studio", "Tools + pipeline 3D"],
        ["04", "COMMERCE", "Market + Mi Spot", "Productos + servicios"],
        ["05", "INFRAESTRUCTURA", "Supabase + Google Cloud", "Datos + assets + deploy"],
      ],
    },
    statement: {
      eyebrow: "PRODUCT THINKING",
      lineOne: "No construí pantallas aisladas.",
      lineTwo: "Construí un sistema de producto conectado.",
      capabilities: ["PRODUCT", "DESIGN", "FRONTEND", "CLOUD", "AI", "3D", "AUTOMATION"],
    },
    featured: {
      index: "02 / SISTEMAS DESTACADOS",
      title: "Tres sistemas que muestran cómo pienso.",
      intro: "La interfaz importa, pero las reglas que hay debajo importan más. Estos casos muestran decisiones de producto detrás de CLOUVA.",
      problem: "PROBLEMA",
      decision: "DECISIÓN DE SISTEMA",
      rail: "RAIL REAL / STACK",
      items: [
        {
          id: "flow",
          status: "IN DEVELOPMENT" as PortfolioStatus,
          eyebrow: "DINERO / SYSTEM DESIGN",
          title: "Mi Flow",
          problem: "El valor interno necesita mantenerse auditable sin convertirse en lo mismo que el estado de pagos de dinero real.",
          decision: "Separar backing, emisión, historial ledger y FLOW disponible. 1 FLOW usa USD 1 como valor de referencia.",
          rail: "Mercado Pago sigue siendo el rail de pago real · Supabase · PostgreSQL",
          pipeline: ["BACKING", "EMISIÓN", "LEDGER", "FLOW DISPONIBLE"],
          image: null,
          imageAlt: "",
          evidenceLabel: "DIAGRAMA DE SISTEMA",
        },
        {
          id: "creator",
          status: "IN DEVELOPMENT" as PortfolioStatus,
          eyebrow: "3D / CREATOR TOOLS",
          title: "Creator Studio",
          problem: "Prendas y avatares necesitan una preparación medible y repetible antes de entrar a un pipeline 3D en tiempo real.",
          decision: "Usar GLB, landmarks, medidas, validación, fitting y procesamiento Blender como flujo canónico de preparación.",
          rail: "GLB · landmarks · medidas · Blender · pipeline Unreal",
          pipeline: ["GARMENT", "ANALYSIS", "VALIDATION", "FIT", "RIG", "EXPORT", "UNREAL"],
          image: PORTFOLIO_V3_ASSETS.creator,
          imageAlt: "Asset real de referencia corporal de Creator Studio del repositorio CLOUVA",
          evidenceLabel: "PIPELINE EN DESARROLLO",
        },
        {
          id: "ai",
          status: "IN DEVELOPMENT" as PortfolioStatus,
          eyebrow: "AI / PRODUCT SYSTEM",
          title: "CLOUVA AI",
          problem: "La IA dentro de un producto necesita contexto, tools y límites de acción, no solamente respuestas de chat.",
          decision: "Pasar la intención del usuario por contexto y tools, exigiendo confirmación cuando una acción tiene consecuencias.",
          rail: "Gemini · multimodal · tool execution · confirmation boundaries · Trébol en desarrollo",
          pipeline: ["USER INTENT", "CONTEXT", "CLOUVA AI", "TOOLS", "CONFIRMATION", "ACTION"],
          image: PORTFOLIO_V3_ASSETS.ai,
          imageAlt: "Asset visual oficial de Trébol utilizado por CLOUVA AI",
          evidenceLabel: "ASSET REAL DEL PRODUCTO",
        },
      ],
    },
    about: {
      eyebrow: "SERGIO / PRODUCT BUILDER",
      title: "Trabajo entre los límites que normalmente separan un producto.",
      body: "Dirección de producto, diseño de interfaces, frontend, implementación asistida por IA, infraestructura cloud y tecnología creativa se conectan en el mismo proceso de construcción.",
      proof: "CLOUVA es la prueba de trabajo: un producto en evolución donde defino funcionalidades, conecto sistemas, valido implementaciones e itero sobre la arquitectura real.",
    },
    deepDive: {
      index: "03 / DEEP DIVE DEL SISTEMA",
      title: "Explorá el resto del producto.",
      intro: "Los sistemas principales y de soporte aparecen con estados honestos LIVE / IN DEVELOPMENT / PLANNED y links directos cuando están disponibles.",
    },
  },
} as const satisfies Record<PortfolioLocale, unknown>;
