"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { PremiumCard, StatCard } from "@/components/os-ui";
import { authenticatedFetch, readApiJson } from "@/lib/authenticated-fetch";

type MoneyRow={currency:string;grossConfirmed:number;providerFees:number;netConfirmed:number;refunds:number};
type Snapshot={flowUsdValue:number;backedAssets:number;circulation:number;unbackedAssets:number;backingDifferenceFlows:number;pendingPurchases:number;confirmedPurchases:number;failedPurchases:number;emissions:number;refundCases:number;refundReviews:number;fundingByCurrency:MoneyRow[]};
type Issue={type:string;severity:string;entityId:string;details:Record<string,unknown>};
type PlayerRef={id:string;display_name:string|null;slug:string|null}|null;
type Funding={id:string;entry_type:string;provider:string;payment_method:string;amount:number;currency:string;status:string;external_payment_id:string|null;provider_fee:number|null;net_amount:number|null;occurred_at:string};
type WalletEntry={id:string;transaction_type:string;amount:number;balance_after:number;source:string|null;reference_id:string|null;created_at:string};
type Operation={id:string;provider:string;provider_payment_id:string|null;provider_reference:string;payment_method:string;quantity:number;unit_usd:number;amount:number;currency:string;status:string;backing_status:string;operation_type:string;target_asset_id:string|null;fx_rate_original_per_usd:number|null;fx_pair:string|null;fx_source:string|null;fx_quoted_at:string|null;provider_fee:number|null;net_amount:number|null;confirmed_at:string|null;issued_at:string|null;refund_status:string|null;created_at:string;buyerPlayer:PlayerRef;recipientPlayer:PlayerRef;funding:Funding[];walletLedger:WalletEntry[]};
type MercadoPagoInfo={enabled:boolean;connected:boolean;environment:string|null;configuredCollectorId:string|null;reportedCollectorId:string|null;matchesConfiguredCollector:boolean|null;nickname:string|null;countryId:string|null;siteStatus:string|null;accountBalance:null;accountBalanceAvailable:false;lookupError?:string};
type Payload={snapshot:Snapshot;reconciliation:Issue[];mercadoPago:MercadoPagoInfo;operations:Operation[]};

const money=(value:number,currency:string)=>new Intl.NumberFormat("es-AR",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value)||0);
const when=(value:string|null)=>value?new Date(value).toLocaleString("es-AR",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const player=(value:PlayerRef)=>value?.slug?`@${value.slug}`:value?.display_name||"—";

export default function FlowTreasuryPage(){
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[open,setOpen]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await authenticatedFetch("/api/admin/flows/treasury");setData(await readApiJson<Payload>(response))}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar Tesorería FLOW.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const s=data?.snapshot;
 return <div className="space-y-4">
  <PremiumCard className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-white/40">Admin · FLOW</p><h1 className="mt-1 text-2xl font-bold">Tesorería / Respaldo FLOW</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-white/50">Auditoría de la cadena pago → respaldo → emisión → ledger → wallet. Los fondos confirmados por pagos no se presentan como saldo bancario de Mercado Pago.</p></div><div className="flex gap-2"><Link href="/admin/flows" className="rounded-xl border border-white/10 px-4 py-2.5 text-sm">Volver</Link><button onClick={()=>void load()} disabled={loading} className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-50">{loading?"Actualizando…":"Actualizar"}</button></div></div></PremiumCard>
  {error?<p className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>:null}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="FLOW respaldados" value={s?.backedAssets??"…"}/><StatCard label="En circulación" value={s?.circulation??"…"}/><StatCard label="Sin respaldo" value={s?.unbackedAssets??"…"}/><StatCard label="Diferencia" value={s?.backingDifferenceFlows??"…"}/></div>
  <div className="grid gap-4 lg:grid-cols-2">
   <PremiumCard className="p-5"><h2 className="font-semibold">Cuenta receptora digital</h2>{data?.mercadoPago?<div className="mt-4 grid gap-2 text-sm"><Row label="Proveedor" value="Mercado Pago"/><Row label="Entorno" value={data.mercadoPago.environment||"—"}/><Row label="Cuenta conectada" value={data.mercadoPago.connected?"Sí":"No"}/><Row label="Collector configurado" value={data.mercadoPago.configuredCollectorId||"—"} mono/><Row label="Collector verificado" value={data.mercadoPago.reportedCollectorId||"—"} mono/><Row label="Coinciden" value={data.mercadoPago.matchesConfiguredCollector===true?"Sí":data.mercadoPago.matchesConfiguredCollector===false?"No":"—"}/>{data.mercadoPago.nickname?<Row label="Nickname" value={data.mercadoPago.nickname}/>:null}<Row label="Saldo actual de cuenta" value="No consultado por esta integración"/>{data.mercadoPago.lookupError?<p className="mt-2 rounded-xl border border-amber-300/15 bg-amber-300/[0.06] p-3 text-xs text-amber-100">{data.mercadoPago.lookupError}</p>:null}</div>:<p className="mt-3 text-sm text-white/40">Cargando…</p>}</PremiumCard>
   <PremiumCard className="p-5"><h2 className="font-semibold">Fondos confirmados por pagos FLOW</h2><div className="mt-4 space-y-3">{s?.fundingByCurrency?.length?s.fundingByCurrency.map(row=><div key={row.currency} className="rounded-xl border border-white/[0.07] bg-black/20 p-3 text-sm"><div className="mb-2 font-semibold">{row.currency}</div><Row label="Bruto confirmado" value={money(row.grossConfirmed,row.currency)}/><Row label="Fees proveedor" value={money(row.providerFees,row.currency)}/><Row label="Neto registrado" value={money(row.netConfirmed,row.currency)}/><Row label="Refunds" value={money(row.refunds,row.currency)}/></div>):<p className="text-sm text-white/40">Sin movimientos confirmados.</p>}</div></PremiumCard>
  </div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><StatCard label="Pendientes" value={s?.pendingPurchases??"…"}/><StatCard label="Pagos confirmados" value={s?.confirmedPurchases??"…"}/><StatCard label="Emisiones" value={s?.emissions??"…"}/><StatCard label="Refunds" value={s?.refundCases??"…"}/><StatCard label="Refunds a revisar" value={s?.refundReviews??"…"}/></div>
  <PremiumCard className="p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Reconciliación automática</h2><p className="mt-1 text-xs text-white/40">Las inconsistencias se detectan; no se corrigen silenciosamente.</p></div><span className={`rounded-full border px-3 py-1 text-xs ${data?.reconciliation?.length?"border-amber-300/20 text-amber-100":"border-emerald-300/20 text-emerald-100"}`}>{data?.reconciliation?.length??"…"} incidencias</span></div><div className="mt-4 space-y-2">{data?.reconciliation?.map(issue=><div key={`${issue.type}:${issue.entityId}`} className="rounded-xl border border-white/[0.07] bg-black/20 p-3 text-xs"><div className="flex justify-between gap-3"><b>{issue.type}</b><span>{issue.severity}</span></div><p className="mt-1 break-all font-mono text-white/40">{issue.entityId}</p></div>)}{data&&data.reconciliation.length===0?<p className="text-sm text-emerald-200">Cadena financiera consistente.</p>:null}</div></PremiumCard>
  <PremiumCard className="p-5"><h2 className="font-semibold">Operaciones</h2><div className="mt-4 space-y-2">{data?.operations.map(operation=>{const expanded=open===operation.id;const funding=operation.funding.find(row=>row.entry_type==="funding"&&row.status==="confirmed");return <div key={operation.id} className="rounded-2xl border border-white/[0.07] bg-black/20"><button onClick={()=>setOpen(expanded?null:operation.id)} className="grid w-full gap-2 p-4 text-left sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><div className="font-medium">{operation.operation_type==="back_existing"?"Respaldar FLOW existente":operation.provider==="cash"?"Compra FLOW · efectivo":"Compra FLOW · Mercado Pago"}</div><div className="mt-1 text-xs text-white/40">{player(operation.recipientPlayer)} · {when(operation.created_at)}</div></div><span className="text-sm">{operation.quantity} FLOW</span><span className="text-sm">{money(operation.amount,operation.currency)}</span></button>{expanded?<div className="grid gap-5 border-t border-white/[0.07] p-4 text-sm lg:grid-cols-2"><div className="grid gap-2"><Row label="Player" value={player(operation.recipientPlayer)}/><Row label="Purchase" value={operation.id} mono/><Row label="Estado" value={`${operation.status} / ${operation.backing_status}`}/><Row label="Provider" value={operation.provider}/><Row label="Método" value={operation.payment_method}/><Row label="Payment ID" value={operation.provider_payment_id||"—"} mono/><Row label="External reference" value={operation.provider_reference} mono/><Row label="Target asset" value={operation.target_asset_id||"—"} mono/></div><div className="grid gap-2"><Row label="Valor FLOW" value={`US$ ${Number(operation.unit_usd).toFixed(2)}`}/><Row label="Importe bruto" value={money(operation.amount,operation.currency)}/><Row label="Fee" value={money(Number(operation.provider_fee||0),operation.currency)}/><Row label="Neto" value={money(Number(operation.net_amount??operation.amount),operation.currency)}/><Row label="FX" value={operation.fx_rate_original_per_usd?`${operation.fx_pair||"USD/ARS"} · ${operation.fx_rate_original_per_usd}`:"No aplica"}/><Row label="Pago confirmado" value={when(operation.confirmed_at)}/><Row label="Emisión" value={when(operation.issued_at)}/><Row label="Funding" value={funding?`${money(funding.amount,funding.currency)} · ${funding.status}`:"—"}/><Row label="Ledger" value={operation.walletLedger.length?operation.walletLedger.map(row=>`${row.transaction_type} ${row.amount>0?"+":""}${row.amount}`).join(" · "):"—"}/></div></div>:null}</div>})}{data&&data.operations.length===0?<p className="text-sm text-white/40">Todavía no hay operaciones FLOW.</p>:null}</div></PremiumCard>
 </div>;
}

function Row({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div className="flex justify-between gap-4"><span className="text-white/40">{label}</span><span className={`break-all text-right ${mono?"font-mono text-[11px]":""}`}>{value}</span></div>}
