export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      categories: { Row: { id: string; name: string; slug: string; image_url: string | null; created_at: string }; Insert: { id?: string; name: string; slug: string; image_url?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['categories']['Insert']>; Relationships: [] };
      products: { Row: { id: string; name: string; slug: string; description: string | null; price: number; old_price: number | null; stock: number; sku: string | null; category_id: string | null; featured: boolean; active: boolean; tags: string[]; sizes: string[]; colors: string[]; created_at: string }; Insert: { id?: string; name: string; slug: string; description?: string | null; price: number; old_price?: number | null; stock?: number; sku?: string | null; category_id?: string | null; featured?: boolean; active?: boolean; tags?: string[]; sizes?: string[]; colors?: string[]; created_at?: string }; Update: Partial<Database['public']['Tables']['products']['Insert']>; Relationships: [] };
      product_images: { Row: { id: string; product_id: string; image_url: string; sort_order: number }; Insert: { id?: string; product_id: string; image_url: string; sort_order?: number }; Update: Partial<Database['public']['Tables']['product_images']['Insert']>; Relationships: [] };
      banners: { Row: { id: string; title: string; subtitle: string | null; image_url: string | null; active: boolean; sort_order: number; created_at: string }; Insert: { id?: string; title: string; subtitle?: string | null; image_url?: string | null; active?: boolean; sort_order?: number; created_at?: string }; Update: Partial<Database['public']['Tables']['banners']['Insert']>; Relationships: [] };
      orders: { Row: { id: string; order_number: number; customer_name: string; customer_phone: string; customer_email: string; customer_address: string; total: number; status: 'pendiente' | 'confirmado' | 'enviado' | 'entregado' | 'cancelado'; created_at: string }; Insert: { id?: string; order_number?: number; customer_name: string; customer_phone: string; customer_email: string; customer_address: string; total: number; status?: 'pendiente' | 'confirmado' | 'enviado' | 'entregado' | 'cancelado'; created_at?: string }; Update: Partial<Database['public']['Tables']['orders']['Insert']>; Relationships: [] };
      order_items: { Row: { id: string; order_id: string; product_id: string | null; quantity: number; unit_price: number; product_name: string }; Insert: { id?: string; order_id: string; product_id?: string | null; quantity: number; unit_price: number; product_name: string }; Update: Partial<Database['public']['Tables']['order_items']['Insert']>; Relationships: [] };
      coupons: { Row: { id: string; code: string; discount_percent: number; active: boolean; created_at: string }; Insert: { id?: string; code: string; discount_percent: number; active?: boolean; created_at?: string }; Update: Partial<Database['public']['Tables']['coupons']['Insert']>; Relationships: [] };
      avatar_items: { Row: { id: string; name: string; category: string; model_url: string; thumbnail_url: string; compatible_skeleton: string; free: boolean; price: number | null; metadata: Json; created_at: string }; Insert: { id?: string; name: string; category: string; model_url: string; thumbnail_url: string; compatible_skeleton: string; free?: boolean; price?: number | null; metadata?: Json; created_at?: string }; Update: Partial<Database['public']['Tables']['avatar_items']['Insert']>; Relationships: [] };
      user_avatars: { Row: { id: string; user_id: string; config: Json; is_active: boolean; created_at: string; updated_at: string }; Insert: { id?: string; user_id: string; config?: Json; is_active?: boolean; created_at?: string; updated_at?: string }; Update: Partial<Database['public']['Tables']['user_avatars']['Insert']>; Relationships: [] };
    };
    Views: Record<string, never>; Functions: Record<string, never>; Enums: Record<string, never>; CompositeTypes: Record<string, never>;
  };
};
