"use client";

import { ArrowLeft, ChevronDown, ChevronUp, Loader2, RefreshCw, ShoppingBag } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { CloverIcon } from "@/components/clover-icon";
import { MainNav } from "@/components/layout";
import { authenticatedFetch, readApiJson } from "@/lib/authenticated-fetch";

type PlayerRef={id:string;display_name:string|null;slug:string|null}|null;
type FundingRef={id:string;entry_type:string;provider:string|null;payment_method:string|null;amount:number;currency:string;status:string;external_payment_id:string|null;provider_fee:number|null;net_amount:number|null;occurred_at:string};
type DocumentRef={id:string;kind:"internal_receipt"|"fiscal_document";status:string;document_number:string|null;external_document_id:string|null;issued_at:string|null};
type MovementRef={id:string;action:string;created_at:string};
type OperationRef={id:string;provider:string;provider_payment_id:string|null;provider_reference:string;payment_method:string;quantity:number;unit_usd:number;amount:number;currency:string;status:string;backing_status:string;confirmed_at:string|null;issued_at:string|null;created_at:string;refund_status:string|null;operation_type:string;target_asset_id:string|null;fx_rate_original_per_usd:number|null;fx_pair:string|null;fx_source:string|null;fx_quoted_at:string|null;provider_fee:number|null;net_amount:number|null;funding:FundingRef[];documents:DocumentRef[];buyerPlayer?:PlayerRef;recipientPlayer?:PlayerRef};
type FlowAsset={id:string;flow_number:number;status:"pending_payment"|"available"|"activated"|"transferred"|"legacy_unverified"|"reversed";issued_at:string;backed_at:string|null;backing_operation_id:string|null;owner:PlayerRef;originalBuyer:PlayerRef;operation:OperationRef|null;originOperation:OperationRef|null;backingOperation:OperationRef|null;history:MovementRef[]};
type Pricing={flowUsdValue:number;referenceCurrency:string;checkoutCurrency:string|null;fxRate:number|null;fxPair:string|null;fxSource:string|null;fxQuotedAt:string|null;quoteSourceDate?:string|null;checkoutUnitAmount:number|null};
type Payload={assets:FlowAsset[];pricing:Pricing;recentOperations:OperationRef[]};

const when=(value:string|null|undefined)=>value?new Date(value).toLocaleString("es-AR",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const money=(value:number,currency:string)=>new Intl.NumberFormat("es-AR",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value)||0);
const player=(value:PlayerRef)=>value?.slug?`@${value.slug}`:value?.display_name||"—";
const origin=(operation:OperationRef|null)=>operation?.provider==="cash"?"Pago en efectivo":operation?.provider==="mercadopago"?"Mercado Pago":operation?.provider||"Sin operación";
const method=(operation:OperationRef|null)=>operation?.payment_method==="cash"?"Efectivo":operation?.payment_method==="mercadopago"?"Mercado Pago":operation?.payment_method||"—";

function operationState(operation:OperationRef){
 if(operation.status==="confirmed"&&operation.issued_at)return "Respaldado / Disponible";
 if(operation.status==="pending"&&operation.provider_payment_id)return "Pago procesándose";
 if(operation.status==="pending")return "Pendiente de pago";
 if(operation.status==="failed")return "Pago rechazado";
 if(operation.status==="cancelled")return "Pago cancelado";
 if(operation.status==="refunded")return "Reembolsado";
 return operation.status;
}

function assetState(asset:FlowAsset){
 if(asset.status==="legacy_unverified")return "Sin respaldar";
 if(asset.status==="reversed"||asset.operation?.backing_status==="reversed")return "Revertido";
 if(asset.operation?.backing_status==="verified"&&asset.operation.status==="confirmed")return "Respaldado";
 if(asset.status==="pending_payment")return "Pendiente de pago";
 if(asset.status==="activated")return "Activado";
 if(asset.status==="transferred")return "Transferido";
 return "Disponible";
}

export default function FlowWalletAssetsPage(){
 const {user,loading:authLoading}=useAuth();
 const [assets,setAssets]=useState<FlowAsset[]>([]),[recentOperations,setRecentOperations]=useState<OperationRef[]>([]),[pricing,setPricing]=useState<Pricing>({flowUsdValue:1,referenceCurrency:"USD",checkoutCurrency:null,fxRate:null,fxPair:null,fxSource:null,fxQuotedAt:null,checkoutUnitAmount:null}),[open,setOpen]=useState<string|null>(null),[loading,setLoading]=useState(true),[buyingKey,setBuyingKey]=useState<string|null>(null),[quantity,setQuantity]=useState(1),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!user)return;setLoading(true);setError(null);try{const response=await authenticatedFetch("/api/flows/assets");const payload=await readApiJson<Payload>(response);setAssets(payload.assets);setPricing(payload.pricing);setRecentOperations(payload.recentOperations||[])}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar tus FLOWS.")}finally{setLoading(false)}},[user]);
 useEffect(()=>{if(authLoading)return;if(!user){setLoading(false);return}void load()},[authLoading,load,user]);
 useEffect(()=>{if(!user||typeof window==="undefined")return;const operation=new URLSearchParams(window.location.search).get("operation");if(!operation)return;const timers=[1500,3500,7000].map(delay=>window.setTimeout(()=>void load(),delay));return()=>timers.forEach(timer=>window.clearTimeout(timer))},[load,user]);
 const pendingOperations=useMemo(()=>recentOperations.filter(operation=>!(operation.status==="confirmed"&&operation.issued_at)),[recentOperations]);
 async function startPurchase(body:Record<string,unknown>,key:string){setBuyingKey(key);setError(null);try{const response=await authenticatedFetch("/api/flows/purchase",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await readApiJson<{initPoint:string}>(response);window.location.assign(payload.initPoint)}catch(e){setError(e instanceof Error?e.message:"No se pudo iniciar el pago.");setBuyingKey(null)}}
 const checkoutEstimate=pricing.checkoutUnitAmount&&pricing.checkoutCurrency?money(pricing.checkoutUnitAmount,pricing.checkoutCurrency):null;
 const totalCheckout=pricing.checkoutUnitAmount&&pricing.checkoutCurrency?money(pricing.checkoutUnitAmount*quantity,pricing.checkoutCurrency):null;
 return <main className="min-h-screen bg-[#07060d] text-white"><MainNav/><div className="mx-auto max-w-5xl space-y-5 px-4 py-8 md:px-8">
  <Link href="/mi-flow/billetera" className="inline-flex items-center gap-2 text-sm text-white/50"><ArrowLeft size={15}/>Volver a Billetera</Link>
  <section className="rounded-[30px] border border-cyan-300/15 bg-gradient-to-br from-[#111b21] via-[#0b1118] to-[#08090d] p-6 md:p-8"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] uppercase tracking-[0.2em] text-cyan-200/60">Billetera · Activos CLOUVA</p><h1 className="mt-2 flex items-center gap-3 text-4xl font-semibold"><CloverIcon className="text-cyan-200" size={34}/>Mis FLOWS</h1><p className="mt-3 text-sm text-white/45">1 FLOW = US$ {pricing.flowUsdValue.toFixed(2)}. Un FLOW monetario queda disponible únicamente después de confirmar su respaldo real.</p></div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-white/10 p-2 text-white/50"><RefreshCw size={15} className={loading?"animate-spin":""}/></button></div></section>
  <section className="rounded-[24px] border border-white/[0.08] bg-[#0c0a13]/95 p-5"><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><p className="font-semibold">Cargar FLOW</p><p className="mt-1 text-xs text-white/40">Valor de referencia: 1 FLOW = US$ {pricing.flowUsdValue.toFixed(2)}{checkoutEstimate?` · cobro estimado ${checkoutEstimate}`:""}.</p>{pricing.fxRate?<p className="mt-1 text-[11px] text-white/30">Checkout en ARS · {pricing.fxPair} {pricing.fxRate} · {pricing.fxSource}. El importe queda fijado al iniciar el pago.</p>:null}</div><input aria-label="Cantidad de FLOW" type="number" min={1} max={50} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(50,Math.trunc(Number(e.target.value)||1))))} className="w-20 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2"/><button onClick={()=>void startPurchase({quantity},"new")} disabled={Boolean(buyingKey)||!pricing.checkoutUnitAmount} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-45">{buyingKey==="new"?<Loader2 size={15} className="animate-spin"/>:<ShoppingBag size={15}/>}+ Cargar FLOW{totalCheckout?` · ${totalCheckout}`:""}</button></div></section>
  {pendingOperations.length?<section className="rounded-[24px] border border-violet-300/10 bg-violet-300/[0.035] p-4"><p className="text-xs uppercase tracking-[0.16em] text-white/40">Operaciones recientes</p><div className="mt-3 space-y-2">{pendingOperations.map(operation=><div key={operation.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/[0.07] bg-black/20 px-3 py-2 text-sm"><div><b>{operation.operation_type==="back_existing"?"Respaldo de FLOW":"Carga de FLOW"}</b><p className="mt-0.5 text-xs text-white/40">{operationState(operation)} · {when(operation.created_at)}</p></div><span>{operation.quantity} FLOW · {money(operation.amount,operation.currency)}</span></div>)}</div></section>:null}
  {error?<p className="rounded-2xl border border-rose-300/15 bg-rose-300/[0.06] p-4 text-sm text-rose-200">{error}</p>:null}{loading?<div className="grid min-h-32 place-items-center"><Loader2 className="animate-spin"/></div>:null}
  <section className="grid gap-4 md:grid-cols-2">{assets.map(asset=>{const operation=asset.operation,receipt=operation?.documents.find(document=>document.kind==="internal_receipt"),fiscal=operation?.documents.find(document=>document.kind==="fiscal_document"),funding=operation?.funding.find(entry=>entry.entry_type==="funding"&&entry.status==="confirmed"),expanded=open===asset.id,isLegacy=asset.status==="legacy_unverified",paymentLabel=operation?operation.status==="confirmed"?(operation.provider==="mercadopago"?"Aprobado":"Confirmado"):operationState(operation):"—";return <article key={asset.id} className="rounded-[24px] border border-cyan-300/10 bg-[#0c0f14] p-5"><button onClick={()=>setOpen(expanded?null:asset.id)} className="w-full text-left"><div className="flex justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.18em] text-white/30">Activo CLOUVA</p><h2 className="mt-1 text-2xl font-semibold">FLOW #{String(asset.flow_number).padStart(6,"0")}</h2><p className="mt-1 text-sm text-white/45">Valor: US$ {pricing.flowUsdValue.toFixed(2)}</p></div><div className="flex items-center gap-2"><span className={`rounded-full border px-3 py-1 text-xs ${isLegacy?"border-amber-200/20 text-amber-100":"border-cyan-200/15 text-cyan-100"}`}>{assetState(asset)}</span>{expanded?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</div></div><div className="mt-4 grid gap-2 text-sm"><Row label="Propietario" value={player(asset.owner)}/><Row label="Origen" value={origin(operation)}/><Row label="Respaldo" value={isLegacy?"Sin respaldar":operation?.backing_status==="verified"?"Pago verificado":operation?.backing_status==="reversed"?"Pago revertido":"Pendiente"}/></div></button>
   {isLegacy?<button onClick={()=>void startPurchase({backExistingAssetId:asset.id},asset.id)} disabled={Boolean(buyingKey)||!pricing.checkoutUnitAmount} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-45">{buyingKey===asset.id?<Loader2 size={15} className="animate-spin"/>:<ShoppingBag size={15}/>}Respaldar FLOW{checkoutEstimate?` · ${checkoutEstimate}`:""}</button>:null}
   {expanded?<div className="mt-5 space-y-5 border-t border-white/[0.07] pt-5"><div><p className="text-[10px] uppercase tracking-[0.16em] text-white/30">Operación de respaldo</p><div className="mt-3 grid gap-2 text-sm"><Row label="Estado" value={assetState(asset)}/><Row label="Método" value={method(operation)}/><Row label="Pago" value={paymentLabel}/><Row label="Valor recibido" value={operation?money(Number(operation.amount),operation.currency):"—"}/><Row label="Pago confirmado" value={when(operation?.confirmed_at)}/><Row label="FLOW respaldado" value={when(asset.backed_at)}/><Row label="Operación" value={operation?.id||"—"} mono/>{operation?.provider==="mercadopago"?<Row label="Payment ID" value={operation.provider_payment_id||"—"} mono/>:null}{funding?<><Row label="Ingreso registrado" value={`${money(Number(funding.amount),funding.currency)} · ${when(funding.occurred_at)}`}/><Row label="Fee proveedor" value={money(Number(funding.provider_fee||0),funding.currency)}/><Row label="Neto registrado" value={money(Number(funding.net_amount??funding.amount),funding.currency)}/></>:null}{operation?.fx_rate_original_per_usd?<Row label="Cotización usada" value={`${operation.fx_pair||"USD/ARS"} · ${operation.fx_rate_original_per_usd}`}/>:null}</div></div><div><p className="text-[10px] uppercase tracking-[0.16em] text-white/30">Origen del activo</p><div className="mt-3 grid gap-2 text-sm"><Row label="Comprador original" value={player(asset.originalBuyer)}/><Row label="FLOW emitido" value={when(asset.issued_at)}/><Row label="Operación origen" value={asset.originOperation?.id||"—"} mono/></div></div><div><p className="text-[10px] uppercase tracking-[0.16em] text-white/30">Comprobantes</p><div className="mt-3 grid gap-2 text-sm"><Row label="Registro interno" value={receipt?.document_number||"—"} mono/><Row label="Comprobante fiscal oficial" value={fiscal?.document_number||"No asociado todavía"}/></div></div><div><p className="text-[10px] uppercase tracking-[0.16em] text-white/30">Historial</p><div className="mt-2 space-y-2">{asset.history.map(history=><div key={history.id} className="flex justify-between rounded-xl bg-white/[0.035] px-3 py-2 text-xs"><span>{history.action}</span><span className="text-white/35">{when(history.created_at)}</span></div>)}</div></div>{operation?.refund_status?<p className="rounded-xl border border-amber-300/15 bg-amber-300/[0.06] p-3 text-xs text-amber-100">El respaldo fue reembolsado o revertido; el caso queda auditado y el FLOW no se borra.</p>:null}</div>:null}
  </article>})}</section>
 </div></main>;
}
function Row({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div className="flex justify-between gap-4"><span className="text-white/35">{label}</span><span className={`break-all text-right ${mono?"font-mono text-[11px] text-white/65":""}`}>{value}</span></div>}
