"use client";
import { useEffect, useState } from "react";
import { MainFooter, MainNav } from "@/components/layout";
import Link from "next/link";
import { loadCart, saveCart } from "@/lib/cart";

type P={id:string;slug:string;name:string;price_cents:number;category:string|null;active:boolean;status?:string|null;product_images?:{image_url:string}[];product_variants?:{stock:number|null}[]};
export default function ShopPage(){
 const [products,setProducts]=useState<P[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{void (async()=>{const {supabase}=await import("@/lib/supabase");const {data}=await supabase.from("products").select("id,slug,name,price_cents,category,active,status,product_images(image_url),product_variants(stock)").eq("active",true).order("name");setProducts((data??[]) as P[]);setLoading(false);})();},[]);
 const add=(p:P)=>{const cart=loadCart(); const idx=cart.findIndex(i=>i.productId===p.id&&i.variant==='default'); if(idx>=0)cart[idx].qty+=1; else cart.push({productId:p.id,slug:p.slug,name:p.name,priceCents:p.price_cents,qty:1,variant:'default'}); saveCart(cart);};
 return <main><MainNav/><section className="mx-auto w-full max-w-7xl px-4 py-14 md:px-8"><h1 className="text-3xl">Tienda CLOUVA</h1><p className="mt-2 text-white/70">Drops premium, streetwear y productos digitales.</p>{loading?<div className="mt-8 rounded-3xl border border-white/10 p-6 text-white/70">Cargando productos...</div>:products.length===0?<div className="mt-8 rounded-3xl border border-white/10 p-6 text-white/70">No hay productos activos todavía.</div>:<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=>{const stock=(p.product_variants??[]).reduce((a,v)=>a+(v.stock??0),0); return <article key={p.id} className="rounded-3xl border border-white/10 bg-white/[0.03] p-4"><div className="aspect-square overflow-hidden rounded-2xl bg-black/30"><img src={p.product_images?.[0]?.image_url||"https://placehold.co/800x800/0f0f17/8f7cff?text=CLOUVA"} alt={p.name} className="h-full w-full object-cover"/></div><div className="mt-3 flex items-center justify-between"><p className="text-xs text-white/60">{p.category??"General"}</p><span className="rounded-full border border-white/20 px-2 py-0.5 text-[10px]">{stock<=3?"Stock bajo":`Stock ${stock}`}</span></div><h3 className="mt-2 text-xl">{p.name}</h3><p className="mt-1 text-[#95d8ff]">${(p.price_cents/100).toLocaleString("es-AR")}</p><div className="mt-3 flex gap-2"><Link href={`/producto/${p.slug}`} className="rounded-full border border-white/20 px-3 py-1.5 text-xs">Ver</Link><button onClick={()=>add(p)} className="rounded-full bg-white px-3 py-1.5 text-xs text-black">Agregar al carrito</button></div></article>})}</div>}</section><MainFooter/></main>
}
