alter table public.user_avatars
  add column if not exists unreal_model_url text,
  add column if not exists unreal_export_metadata jsonb,
  add column if not exists unreal_exported_at timestamptz;

comment on column public.user_avatars.unreal_model_url is 'Validated FBX prepared specifically for Unreal Engine; original and general rigged GLB remain unchanged.';
comment on column public.user_avatars.unreal_export_metadata is 'Bounding-box, scale, rig and grounding validation generated by Blender Worker.';
