create table if not exists public.unreal_avatar_snapshots (
  id bigint generated by default as identity primary key,
  preset_name text not null,
  actor_name text not null,
  status text not null check (status in ('online', 'offline')),
  captured_at timestamptz not null,
  last_connected_at timestamptz not null,
  snapshot jsonb not null,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists unreal_avatar_snapshots_preset_captured_idx
  on public.unreal_avatar_snapshots (preset_name, captured_at desc);

alter table public.unreal_avatar_snapshots enable row level security;

revoke all on table public.unreal_avatar_snapshots from anon, authenticated;
