create extension if not exists pgcrypto;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  price numeric(12,2) not null default 0,
  old_price numeric(12,2),
  stock integer not null default 0,
  sku text unique,
  category_id uuid references public.categories(id) on delete set null,
  featured boolean not null default false,
  active boolean not null default true,
  tags text[] not null default '{}',
  sizes text[] not null default '{}',
  colors text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  customer_name text not null,
  customer_phone text not null,
  customer_email text not null,
  customer_address text not null,
  total numeric(12,2) not null default 0,
  status text not null default 'pendiente' check (status in ('pendiente','confirmado','enviado','entregado','cancelado')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null,
  product_name text not null
);

create table if not exists public.banners (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subtitle text,
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount_percent integer not null check (discount_percent between 1 and 100),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.banners enable row level security;
alter table public.coupons enable row level security;

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select using (true);
drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products for select using (active = true or auth.role() = 'authenticated');
drop policy if exists "public read product images" on public.product_images;
create policy "public read product images" on public.product_images for select using (true);
drop policy if exists "public read active banners" on public.banners;
create policy "public read active banners" on public.banners for select using (active = true or auth.role() = 'authenticated');
drop policy if exists "public create orders" on public.orders;
create policy "public create orders" on public.orders for insert with check (true);
drop policy if exists "public create order items" on public.order_items;
create policy "public create order items" on public.order_items for insert with check (true);

create policy "authenticated manage categories" on public.categories for all to authenticated using (true) with check (true);
create policy "authenticated manage products" on public.products for all to authenticated using (true) with check (true);
create policy "authenticated manage product images" on public.product_images for all to authenticated using (true) with check (true);
create policy "authenticated manage orders" on public.orders for all to authenticated using (true) with check (true);
create policy "authenticated manage order items" on public.order_items for all to authenticated using (true) with check (true);
create policy "authenticated manage banners" on public.banners for all to authenticated using (true) with check (true);
create policy "authenticated manage coupons" on public.coupons for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public) values ('products','products',true), ('categories','categories',true), ('banners','banners',true) on conflict (id) do update set public = excluded.public;

create policy "public read store media" on storage.objects for select using (bucket_id in ('products','categories','banners'));
create policy "authenticated upload store media" on storage.objects for insert to authenticated with check (bucket_id in ('products','categories','banners'));
create policy "authenticated update store media" on storage.objects for update to authenticated using (bucket_id in ('products','categories','banners')) with check (bucket_id in ('products','categories','banners'));
create policy "authenticated delete store media" on storage.objects for delete to authenticated using (bucket_id in ('products','categories','banners'));
