name: NinotimiTools
version: 2.0.0
main: ar.com.clouva.ninotimi.NinotimiTools
api-version: '26.2'
author: CLOUVA
description: NINOTIMI builder tools + PVP portal/arena
commands:
  nrtools:
    description: Abre y administra NINOTIMI TOOLS
    aliases: [tools, herramientas, ninotimi]
    usage: /nrtools [grant|revoke|list|give]
  pvp:
    description: Controla NINOTIMI PVP
    usage: /pvp [join|leave|lobby|spectate|status|portalhere|rebuild]
  hielo:
    description: Controla BATALLA DE HIELO
    aliases: [ice, spleef]
    usage: /hielo [join|leave|lobby|spectate|status|portalhere|rebuild]
  npcgame:
    description: Crea y administra aldeanos que llevan a juegos
    aliases: [juegosnpc, gamevillager]
    usage: /npcgame [create|remove|list]
  skyblock:
    description: Controla NINOTIMI SKYBLOCK
    aliases: [sb, sky]
    usage: /skyblock [home|create|lobby|leave|visit|status|portalhere|rebuild]
  parkour:
    description: Abre y controla NINOTIMI PARKOUR
    aliases: [pk, park]
    usage: /parkour [menu|1|2|3|restart|leave|rebuild]
  survival:
    description: Abre NINOTIMI SURVIVAL personal, común o HARDCORE
    aliases: [survi, sv]
    usage: /survival [menu|personal|comun|hardcore|leave|status|portalhere|reset]
  lobby:
    description: Vuelve al lobby principal de NINOTIMI
    aliases: [hub, spawn]
    usage: /lobby
permissions:
  ninotimi.tools:
    description: Puede usar NINOTIMI TOOLS
    default: op
