name: NinotimiTools
version: 2.0.0
main: ar.com.clouva.ninotimi.NinotimiTools
api-version: '26.2'
author: CLOUVA
description: NINOTIMI builder tools + PVP portal/arena
commands:
  nrtools:
    description: Abre y administra NINOTIMI TOOLS
    aliases: [tools, herramientas, ninotimi]
    usage: /nrtools [grant|revoke|list|give]
  pvp:
    description: Controla NINOTIMI PVP
    usage: /pvp [join|leave|lobby|spectate|status|portalhere|rebuild]
  hielo:
    description: Controla BATALLA DE HIELO
    aliases: [ice, spleef]
    usage: /hielo [join|leave|lobby|spectate|status|portalhere|rebuild]
  skyblock:
    description: Controla NINOTIMI SKYBLOCK
    aliases: [sb, sky]
    usage: /skyblock [home|create|lobby|leave|visit|status|portalhere|rebuild]
permissions:
  ninotimi.tools:
    description: Puede usar NINOTIMI TOOLS
    default: op
